sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11628262#notes
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc # source is more or less similar to "execute"
  - gcloud component update kubectl #install kubectl inside travis environment
  - gcloud auth activate-service-account --key-file service-account.json # autorizing the google cloud account
  - gcloud config set project multi-k8s-326906 # this one 'multi-k8s-326906' is the google cloud project name
  - gcloud config set compute/zone europe-central2-a
  - gcloud container clusters get-credentials cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # we used this command before
  - docker build -t brianenno/yes-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brianenno/yes-react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh # following you will find the sh script. explanation: https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11628234?start=142#notes
  on:
    branch: master